version: "3"
services:
  dev-core:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./:/sbdia_cs
      - '/sbdia_cs/Backend/ClientApp/node_modules'
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true